[package]
name = "watter"
version = "0.1.0"
edition = "2021"



[dependencies]
web3 =   "0.19.0" 
tokio = { version = "1.39.1", features = ["full"] }
secp256k1 = "0.29.0"
hex = "0.4"
bip39 = "2.0.0"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"